language: nix

before_install:
  - export GHCJS_BOOTING=1
  - export GHCJS_BOOTING_STAGE1=1
  - export PATH=$HOME/.cabal/bin:$PATH

install:
  - nix-env -i cabal-install haskellPackages.happy haskellPackages.alex
  - nix-shell --argstr compiler ghc7102 --run 'cabal install --enable-tests --enable-benchmarks -v -j1 --ghc-options="+RTS -c -RTS"'
  - nix-shell --argstr compiler ghc7102 --run './test/runTravis.sh boot'

script:
  - nix-shell --argstr compiler ghc7102 --run './test/runTravis.sh test'

branches:
  only:
    - gh-pages
    - /.*/

sudo: false
